version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - misspell
    - revive
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 25
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/sftpgo/sftpgo-plugin-geoipfilter
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
