name: Build

on:
  push:
    branches: [main]
  pull_request:

env:
  GO_VERSION: '1.20'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y osslsigncode
          go install github.com/tc-hib/go-winres@latest

          GIT_COMMIT=`git describe --always --dirty`
          LATEST_TAG=$(git describe --always --tags $(git rev-list --tags --max-count=1))
          NUM_COMMITS_FROM_TAG=$(git rev-list ${LATEST_TAG}.. --count)
          VERSION=$(echo "${LATEST_TAG}" | awk -F. -v OFS=. '{$NF++;print}')-dev.${NUM_COMMITS_FROM_TAG}
          FILE_VERSION=${LATEST_TAG:1}.${NUM_COMMITS_FROM_TAG}

          mkdir bin
          go-winres simply --arch amd64 --product-version $VERSION-$GIT_COMMIT --file-version $FILE_VERSION --file-description "SFTPGo plugin geoipfilter" --product-name "SFTPGo plugin geoipfilter" --copyright "AGPL-3.0" --original-filename sftpgo-plugin-geoipfilter-windows-x86_64.exe --icon res/icon.ico
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.commitHash=`git describe --always --dirty` -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.buildDate=`date -u +%FT%TZ`" -o sftpgo-plugin-geoipfilter-windows-x86_64.exe
          go-winres simply --arch arm64 --product-version $VERSION-$GIT_COMMIT --file-version $FILE_VERSION --file-description "SFTPGo plugin geoipfilter" --product-name "SFTPGo plugin geoipfilter" --copyright "AGPL-3.0" --original-filename sftpgo-plugin-geoipfilter-windows-arm64.exe --icon res/icon.ico
          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -trimpath -ldflags "-s -w -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.commitHash=`git describe --always --dirty` -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.buildDate=`date -u +%FT%TZ`" -o sftpgo-plugin-geoipfilter-windows-arm64.exe
          go-winres simply --arch 386 --product-version $VERSION-$GIT_COMMIT --file-version $FILE_VERSION --file-description "SFTPGo plugin geoipfilter" --product-name "SFTPGo plugin geoipfilter" --copyright "AGPL-3.0" --original-filename sftpgo-plugin-geoipfilter-windows-x86.exe --icon res/icon.ico
          CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -trimpath -ldflags "-s -w -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.commitHash=`git describe --always --dirty` -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.buildDate=`date -u +%FT%TZ`" -o sftpgo-plugin-geoipfilter-windows-x86.exe
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            mv sftpgo-plugin-geoipfilter-windows-x86_64.exe bin/
            mv sftpgo-plugin-geoipfilter-windows-arm64.exe bin/
            mv sftpgo-plugin-geoipfilter-windows-x86.exe bin/
          else
            echo $CERT_DATA | base64 --decode > cert.pfx
            osslsigncode sign -pkcs12 cert.pfx -pass $CERT_PASS -n "SFTPGo plugin geoipfilter" -i "https://github.com/sftpgo/sftpgo-plugin-geoipfilter" -ts "http://timestamp.sectigo.com" -h sha2 -in sftpgo-plugin-geoipfilter-windows-x86_64.exe -out bin/sftpgo-plugin-geoipfilter-windows-x86_64.exe
            osslsigncode sign -pkcs12 cert.pfx -pass $CERT_PASS -n "SFTPGo plugin geoipfilter" -i "https://github.com/sftpgo/sftpgo-plugin-geoipfilter" -ts "http://timestamp.sectigo.com" -h sha2 -in sftpgo-plugin-geoipfilter-windows-arm64.exe -out bin/sftpgo-plugin-geoipfilter-windows-arm64.exe
            osslsigncode sign -pkcs12 cert.pfx -pass $CERT_PASS -n "SFTPGo plugin geoipfilter" -i "https://github.com/sftpgo/sftpgo-plugin-geoipfilter" -ts "http://timestamp.sectigo.com" -h sha2 -in sftpgo-plugin-geoipfilter-windows-x86.exe -out bin/sftpgo-plugin-geoipfilter-windows-x86.exe
            rm -f cert.pfx
          fi

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.commitHash=`git describe --always --dirty` -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.buildDate=`date -u +%FT%TZ`" -o bin/sftpgo-plugin-geoipfilter-linux-amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -trimpath -ldflags "-s -w -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.commitHash=`git describe --always --dirty` -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.buildDate=`date -u +%FT%TZ`" -o bin/sftpgo-plugin-geoipfilter-linux-arm64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -trimpath -ldflags "-s -w -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.commitHash=`git describe --always --dirty` -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.buildDate=`date -u +%FT%TZ`" -o bin/sftpgo-plugin-geoipfilter-linux-armv7
          CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le go build -trimpath -ldflags "-s -w -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.commitHash=`git describe --always --dirty` -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.buildDate=`date -u +%FT%TZ`" -o bin/sftpgo-plugin-geoipfilter-linux-ppc64le
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "-s -w -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.commitHash=`git describe --always --dirty` -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.buildDate=`date -u +%FT%TZ`" -o bin/sftpgo-plugin-geoipfilter-darwin-amd64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -trimpath -ldflags "-s -w -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.commitHash=`git describe --always --dirty` -X github.com/sftpgo/sftpgo-plugin-geoipfilter/cmd.buildDate=`date -u +%FT%TZ`" -o bin/sftpgo-plugin-geoipfilter-darwin-arm64
        shell: bash
        env:
          CERT_DATA: ${{ secrets.CERT_DATA }}
          CERT_PASS: ${{ secrets.CERT_PASS }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: sftpgo-plugin-geoipfilter
          path: bin

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest